---
- name: "Create Custom"
- name: Install Pipenv
  pip:
    name: pipenv
- name: Pulldown Flask Code
  git:
    repo: '{{ git_repo }}'
    dest: '{{ app.project_dir }}'
- name: Install python requirements
  command: chdir={{ app.project_dir }} pipenv install
- name: Install nginx
  yum: name=nginx state=present
  - name: Copy nginx config for flask proxy 
    template: src=dev-ops-demo.j2 dest=/ect/nginx/sites-available/dev-ops-demo
    notify: restart nginx
  - name: Copy health check file over
    copy: 
      src: health.html 
      dest: /var/www/public_html/health.html
  - name: Copy index file over
    copy: 
      src: health.html 
      dest: /var/www/public_html/index.html
  - name: Link sites available to sites enableed
    command: ln -s /etc/nginx/sites-available/{{ app.project_name }} /etc/nginx/sites-enabled


